export const ACTION_TYPES = {
    TOGGLE_LOADING: "TOGGLE_LOADING",
    SHOW_TOAST: "SHOW_TOAST",
    UPDATE_EVENTS: "UPDATE_EVENTS",
    UPDATE_FILTERED_EVENTS: "UPDATE_FILTERED_EVENTS",
    UPDATE_SELECTED_EVENTS: "UPDATE_SELECTED_EVENTS",
    UPDATE_SELECTED_ID_MAP: "UPDATE_SELECTED_ID_MAP",
    UPDATE_EVENT_COUNT: "UPDATE_EVENT_COUNT"
};